export const RoutePaths = {
  HOME: '/',
  HERO: 'hero',
  TESTIMONIALS: 'testimonials',
  ABOUT: 'about',
  CONTACTLIST: '/contact-list',
  CONTACTFORM: '/contact-form',
  PRIVACY: 'privacy',
  COOKIE: 'cookie',
  POST: 'post',
  NEWS: 'news',
  ADMIN: 'admin',
  POSTFORM: 'postForm',
  HEALTH: 'health',
  DOCTRINE: 'doctrine',
  SABBATHSCHOOL: 'sabbathSchool',
  DASHBOARD: 'dashboard',
  VOLUNTARY: 'voluntary',
  NOTIFYEMAIL: 'notifyEmail',
  ALBUM: 'album',
  ALBUMFORM: 'albumForm',
  OFFICERS: 'officers',
  VIDEOPOST: 'videopost',
  POSTSPAGE: 'postsPage',
  VIDEOPOSTFORM: 'videopostForm',
  ACCESS: '/access',
  REMOVE_POST: 'remove-post',
};
