export const RoutePaths = {
    ROOT: '/',
    HERO: '/',
    TESTIMONIALS:'testimonials',
    ABOUT: 'about',
    CONTACTLIST: 'contactList',
    CONTACT: 'contact',
    PRIVACY: 'privacy',
    COOKIE: 'cookie',
    POST: 'post',
    NEWS: 'news',
    ADMIN: 'admin',
    POSTFORM: 'postForm',
    HEALTH: 'health',
    DOCTRINE: 'doctrine',
    SABBATHSCHOOL: 'sabbathSchool',
    DASHBOARD: 'dashboard',
    SIGNUP: 'signup',
    NOTIFYEMAIL: 'notifyEmail',
    SIGNUP: 'signup',
}