export const RoutePaths = {
    ROOT: '/',
    HOME: '/',
    HERO: 'hero',
    TESTIMONIALS:'testimonials',
    ABOUT: 'about',
    CONTACTLIST: 'contactList',
    CONTACT: 'contact',
    PRIVACY: 'privacy',
    COOKIE: 'cookie',
    POST: 'post',
  
    NEWS: 'news',
    ADMIN: 'admin',
    POSTFORM: 'postForm',
    HEALTH: 'health',
    DOCTRINE: 'doctrine',
    SABBATHSCHOOL: 'sabbathSchool',
    DASHBOARD: 'dashboard',
   VOLUNTARY: 'voluntary',
    NOTIFYEMAIL: 'notifyEmail',
    GALLERY: 'gallery',
    OFFICERS: 'officers',
    VIDEOPOST: 'videopost',
    POSTSPAGE: 'postsPage',
    VIDEOPOSTFORM: 'videopostForm',
   
}